I = imread('cameraman.tif');
       subplot(2,2,1);imshow(I);title('Original Image'); 
       H = fspecial('unsharp',0.2);
       sharpened = imfilter(I,H,'replicate');
       subplot(2,2,2);imshow(sharpened);title('Sharpened Image 0.2');
       H = fspecial('unsharp',0.4);
       sharpened = imfilter(I,H,'replicate');
       subplot(2,2,3);imshow(sharpened);title('Sharpened Image 0.4');
       H = fspecial('unsharp',0.8);
       sharpened = imfilter(I,H,'replicate');
       subplot(2,2,4);imshow(sharpened);title('Sharpened Image 0.8');